name: cxr
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - pyyaml
  - tqdm
  - pip
  - pip:
      - albumentations
      - opencv-python-headless
      - streamlit
